// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcPU7U3FQ5ljo9lDiAOT0VDi7PaL7SyN4',
    appId: '1:949824390076:web:e1454c32404b8872a961b9',
    messagingSenderId: '949824390076',
    projectId: 'homework4-msg-board-app',
    authDomain: 'homework4-msg-board-app.firebaseapp.com',
    storageBucket: 'homework4-msg-board-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzX1qTv87IedwnPgOTwfg7uKpRUsvEaas',
    appId: '1:949824390076:android:3b5236b1fe1e8635a961b9',
    messagingSenderId: '949824390076',
    projectId: 'homework4-msg-board-app',
    storageBucket: 'homework4-msg-board-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcPU7U3FQ5ljo9lDiAOT0VDi7PaL7SyN4',
    appId: '1:949824390076:web:192079e3402acce2a961b9',
    messagingSenderId: '949824390076',
    projectId: 'homework4-msg-board-app',
    authDomain: 'homework4-msg-board-app.firebaseapp.com',
    storageBucket: 'homework4-msg-board-app.firebasestorage.app',
  );
}
